
version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3308:3308"
    networks:
      - mynetwork

  java-app:
    build: .
    container_name: java-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:

