version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fx_deals
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
    networks:
      - mynetwork

  java-app:
    build: .
    container_name: java-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fx_deals?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

networks:
  mynetwork:
